#!/usr/bin/env python
"""Perform a pingall operation
Command line handler to do a pingall in each one
of the distributed topologies 
"""

import util.mininet_handler_util as h_util


def pingall_handler_main():
    """Main
    Send a POST request to the master 'ping_all' endpoint, 
    validate the response code and print the responses

    Usage: 
      ./pingall_handler --json-config <path-to-json-conf>

    Example:
      ./pingall_handler --json-config config/handler_config.json

    Command Line Arguments:
      json-config (str): Path to the JSON configuration file to be used
    """
    conf = h_util.parse_json_conf()

    res = h_util.master_cmd(conf['master_host'],
                            conf['master_port'],
                            'ping_all',
                            conf['ip_list'])

    h_util.handle_post_request(res, exit_on_fail=False)

if __name__ == '__main__':
    pingall_handler_main()
