#!/usr/bin/env python
"""Start the topologies
Command line handler to start the distributed topologies
"""

import util.mininet_handler_util as h_util


def start_handler_main():
   """Main
    Send a POST request to the master 'start' endpoint, 
    validate the response code and print the responses

    Usage: 
      ./start_topology_handler --json-config <path-to-json-conf>

    Example:
      ./start_topology_handler --json-config config/handler_config.json

    Command Line Arguments:
      json-config (str): Path to the JSON configuration file to be used
    """
    conf = h_util.parse_json_conf()

    res = h_util.master_cmd(conf['master_host'],
                            conf['master_port'],
                            'start',
                            conf['worker_ip_list'])

    h_util.handle_post_request(res, exit_on_fail=True)

if __name__ == '__main__':
    start_handler_main()
