#!/usr/bin/env python
"""Stop the topologies
Command line handler to stop the distributed topologies
"""

import util.mininet_handler_util as h_util


def stop_handler_main():
   """Main
    Send a POST request to the master 'stop' endpoint, 
    validate the response code and print the responses

    Usage: 
      ./stop_topology_handler --json-config <path-to-json-conf>

    Example:
      ./stop_topology_handler --json-config config/handler_config.json

    Command Line Arguments:
      json-config (str): Path to the JSON configuration file to be used
    """
    conf = h_util.parse_json_conf()

    res = h_util.master_cmd(conf['master_host'],
                            conf['master_port'],
                            'stop',
                            conf['worker_ip_list'])

    h_util.handle_post_request(res, exit_on_fail=True)

if __name__ == '__main__':
    stop_handler_main()
